package packagetest.sampleenumpackage;

import java.lang.Exception;
import java.lang.Integer;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * Generated by ClassFactoryProcessor.
 * @see org.vermeer1977.infrastructure.annotation.processor.ClassFactoryProcessor
 * @see org.vermeer1977.infrastructure.annotation.processor.resource
 */
public enum Message6 {
  /**
   * メッセージ００１<br>
   * parameter count = 0
   */
  MSG001("msg001", 0, "メッセージ００１"),

  /**
   * メッセージ００２{0}と{1}<br>
   * parameter count = 2
   */
  MSG002("msg002", 2, "メッセージ００２{0}と{1}");

  private static ResourceBundle.Control control;

  private static Locale locale;

  private final String key;

  private final Integer paramCount;

  private final String value;

  private Message6(String key, Integer paramCount, String value) {
    this.key = key;
    this.paramCount = paramCount;
    this.value = value;
  }

  /**
   * 任意設定項目：ResourceBundleから値を取得する際に使用するControlを設定する.<br>
   * 未設定の場合、ResourceBundleのデフォルトで処理します.<br>
   * 本設定はロケールのFallbackを設定したい場合などに使用します.<br>Caution:this feild is Thread-Unsafe.
   *
   */
  public static void setControl(ResourceBundle.Control control) {
    Message6.control = control;
  }

  /**
   * 任意設定項目：ResourceBundleから値を取得する際に使用するLocaleを設定する.<br>
   * 未設定の場合、デフォルトロケールで処理します.<br>
   * Caution:this feild is Thread-Unsafe.
   *
   */
  public static void setLocale(Locale locale) {
    Message6.locale = locale;
  }

  /**
   * リソースの値を返却する.<br>
   * 例外捕捉時の対応については、リソースの取得が出来なかった場合に最低限状況判別が出来うるメッセージを表示させるための措置.<br>
   * あわせて、メッセージIDを付与することでリソースの取得が出来ていなかったことを可視できるようにしておく.<br>
   * @return 当該定数に該当するリソースの値
   */
  @Override
  public String toString() {
    try {
      java.util.Locale _locale = Message6.locale == null ? java.util.Locale.getDefault() : Message6.locale;
      if (Message6.control == null) {
        return java.util.ResourceBundle.getBundle("resource.message6", _locale).getString(this.key);
      }
      return java.util.ResourceBundle.getBundle("resource.message6", _locale, Message6.control).getString(this.key);
    } catch(Exception ex) {
      return this.value;
    }
  }

  /**
   * 埋め込み文字を置換した文字列を返却する.<br>
   * 例外捕捉時の対応については、リソースの取得が出来なかった場合に最低限状況判別が出来うるメッセージを表示させるための措置.<br>
   * あわせて、メッセージIDを付与することでリソースの取得が出来ていなかったことを可視できるようにしておく.
   * @return 埋め込み文字を置換した文字列
   */
  public String format(Object... params) {
    return java.text.MessageFormat.format(toString(), params);
  }
}
